(()=>{'use strict';const RAW='./',rf=n=>RAW+encodeURIComponent(n),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],B={hb:rf('ChatGPT Image 24 сент. 2026 г., 17_33_23 (1).png'),hg:rf('ChatGPT Image 24 сент. 2026 г., 17_33_24 (2).png'),ef:rf('ChatGPT Image 24 сент. 2026 г., 17_33_25 (4).png'),er:rf('ChatGPT Image 24 сент. 2026 г., 17_33_25 (3).png'),bf:rf('ChatGPT Image 24 сент. 2026 г., 17_33_26 (5).png'),bm:rf('ChatGPT Image 24 сент. 2026 г., 17_33_27 (6).png'),bn:rf('ChatGPT Image 24 сент. 2026 г., 17_33_27 (7).png')};function def(){return{title:'Догони, если сможешь',lives:3,timer:60,enemySpeed:.55,par:1,sound:true,vol:.6,heroSize:104,heroFlip:false,enemySize:104,bonusCount:3,bonusSize:54,ts:{on:true,bg:'#ffffff',border:'#b9dacc',borderWidth:1,titleFont:'system',textFont:'system',titleColor:'#17382c',textColor:'#51665c',titleSize:32,textSize:15,title:'Догони, если сможешь',text:'Собери бонусы, выполни задания и не дай сопернику догнать тебя.',img:'',btn:'Начать игру'},end:{w:{title:'Победа!',text:'Отличная игра — все бонусы собраны!',img:'',bg:'#e9fff4',color:'#123d2f',btn:'#16b978'},l:{title:'Поражение',text:'Попробуй ещё раз — получится!',img:'',bg:'#fff0f0',color:'#5c2626',btn:'#df5b5b'}},a:{hero:B.hb,enemy:B.ef,bf:B.bf,bm:B.bm,bn:B.bn,bg:'',bonus:fallbackImage('bonus'),ob:fallbackImage('ob')},obs:[{x:700,w:78,h:72},{x:1190,w:86,h:80}],tasks:[{type:'single',q:'Какой вариант правильный?',options:['Ответ 1','Ответ 2','Ответ 3'],ok:'1',fb:'Отлично!'},{type:'text',q:'Введите правильный ответ',options:[],ok:'ответ',fb:'Верно.'},{type:'order',q:'Расставьте элементы по порядку',options:['Первый','Второй','Третий'],ok:'1,2,3',fb:'Правильно.'}],d:{qFont:'system',aFont:'system',cardBg:'#ffffff',qColor:'#17382c',aColor:'#17382c',qSize:22,aSize:16,aBg:'#f7fbf9',btnBg:'#16b978'}}}
const el=id=>document.getElementById(id), embedded=window.DOGONI_PROJECT, types={single:'Один ответ',multiple:'Несколько ответов',text:'Ввод ответа',oral:'Устный ответ',order:'Порядок'};
let P=def(),sel=0,tab='p0',finalKind='w',rt=null,raf=0,test=false,hold={left:false,right:false,down:false},au,db,saveTimer,stored=null,epoch=0,revision=0,preparedExport=null;
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
const fonts={system:'system-ui, sans-serif',Arial:'Arial, sans-serif',Verdana:'Verdana, sans-serif',Georgia:'Georgia, serif','Trebuchet MS':'Trebuchet MS, sans-serif','Courier New':'Courier New, monospace'};
const font=k=>fonts[k]||fonts.system;
const clamp=(v,a,b,d)=>Number.isFinite(+v)?Math.max(a,Math.min(b,+v)):d;
function normalize(p){if(!p||typeof p!=='object'||Array.isArray(p))throw Error('Неверный формат проекта');let d=def(),n={...d,...p,a:{...d.a,...p.a},d:{...d.d,...p.d},ts:{...d.ts,...p.ts},end:{w:{...d.end.w,...p.end?.w},l:{...d.end.l,...p.end?.l}}};n.lives=clamp(n.lives,1,99,3);n.timer=clamp(n.timer,0,3600,60);n.bonusCount=Math.round(clamp(n.bonusCount,0,30,3));for(const [k,a,b] of [['heroSize',50,180],['enemySize',50,180],['bonusSize',36,90],['enemySpeed',.1,2.5],['par',.2,3],['vol',0,1]])n[k]=clamp(n[k],a,b,d[k]);for(const k of Object.keys(n.a)){if(!safeImage(n.a[k]))n.a[k]=d.a[k];}for(const o of [n.ts,n.end.w,n.end.l]){if(!safeImage(o.img))o.img='';}for(const k of ['cardBg','qColor','aColor','aBg','btnBg'])if(!/^#[0-9a-f]{6}$/i.test(n.d[k]))n.d[k]=d.d[k];for(const [k,a,b] of [['qSize',14,40],['aSize',12,32]])n.d[k]=clamp(n.d[k],a,b,d.d[k]);for(const k of ['w','l'])for(const c of ['bg','color','btn'])if(!/^#[0-9a-f]{6}$/i.test(n.end[k][c]))n.end[k][c]=d.end[k][c];n.tasks=Array.isArray(p.tasks)?p.tasks.slice(0,30).map(t=>({type:types[t?.type]?t.type:'single',q:String(t?.q||'Новое задание'),options:Array.isArray(t?.options)?t.options.map(String):[],ok:String(t?.ok??'1'),fb:String(t?.fb||'')})):d.tasks;n.obs=Array.isArray(p.obs)?p.obs.filter(o=>o&&Number.isFinite(+o.x)).map(o=>({x:clamp(o.x,360,20000,700),w:clamp(o.w,30,120,78),h:clamp(o.h,30,100,72)})):d.obs;for(const c of ['bg','border','titleColor','textColor'])if(!/^#[0-9a-f]{6}$/i.test(n.ts[c]))n.ts[c]=d.ts[c];
for(const [k,a,b] of [['titleSize',18,64],['textSize',12,36],['borderWidth',0,8]])n.ts[k]=clamp(n.ts[k],a,b,d.ts[k]);
for(const [o,k] of [[n.ts,'titleFont'],[n.ts,'textFont'],[n.d,'qFont'],[n.d,'aFont']])if(!Object.hasOwn(fonts,o[k]))o[k]='system';
n.heroFlip=!!n.heroFlip;return n;}
function safeImage(s){return !s||['bonus','ob','hero'].some(k=>s===fallbackImage(k))||/^(data:image\/(png|jpeg|jpg|gif|webp);base64,|https?:\/\/|\.\/)/i.test(s);}
function notify(s){if(el('status'))el('status').textContent=s;}
function taskNotice(s){if(el('taskStatus'))el('taskStatus').textContent=s;}
function invalidateExport(){revision++;preparedExport=null;if(el('exportStatus'))el('exportStatus').textContent='';if(el('miniBtn'))el('miniBtn').setAttribute('aria-pressed','false');}
function openDB(){return new Promise(resolve=>{try{const q=indexedDB.open('dogoni-editor',1);q.onupgradeneeded=()=>q.result.createObjectStore('projects');q.onsuccess=()=>resolve(q.result);q.onerror=()=>resolve(null);}catch{resolve(null);}});}
function dbGet(){return new Promise(resolve=>{if(!db)return resolve(null);const q=db.transaction('projects').objectStore('projects').get('current');q.onsuccess=()=>resolve(q.result||null);q.onerror=()=>resolve(null);});}
async function persist(){clearTimeout(saveTimer);if(embedded)return;const snapshot=JSON.parse(JSON.stringify(P));try{if(db)await new Promise((res,rej)=>{let tx=db.transaction('projects','readwrite');tx.objectStore('projects').put(snapshot,'current');tx.oncomplete=res;tx.onerror=()=>rej(tx.error);tx.onabort=()=>rej(tx.error);});else localStorage.setItem('dogoniProject',JSON.stringify(snapshot));notify('Все изменения сохранены');return true;}catch{notify('Автосохранение недоступно. Сохраните проект в JSON кнопкой «Сохранить».');return false;}}
function changed(){invalidateExport();if(test)stopGame();notify('Сохраняем…');clearTimeout(saveTimer);saveTimer=setTimeout(persist,220);renderPreview();}
function syncTasks(){while(P.tasks.length<P.bonusCount)P.tasks.push({type:'single',q:'Новое задание '+(P.tasks.length+1),options:['Вариант 1','Вариант 2'],ok:'1',fb:''});P.tasks.length=P.bonusCount;sel=Math.max(0,Math.min(sel,P.tasks.length-1));syncObstacles();}
function syncObstacles(){P.obs=Array.from({length:P.bonusCount},(_,i)=>({x:420+i*360,w:78,h:72}));}
function bind(id,get,set,after){let e=el(id);e.type==='checkbox'?e.checked=get():e.value=get();const update=()=>{set(e.type==='checkbox'?e.checked:e.value);if(e.type==='range')e.nextElementSibling.value=e.value;after?.();changed();};if(e.type==='number'){e.oninput=null;e.onchange=()=>{if(e.value!=='')update();};}else e.oninput=update;if(e.type==='range'){let out=e.nextElementSibling;if(!out||out.tagName!=='OUTPUT'){out=document.createElement('output');e.after(out);}out.value=e.value;}}
function fill(){for(const k of ['title','lives','timer','enemySpeed','vol','heroSize','enemySize','par','bonusCount','bonusSize'])bind(k,()=>P[k],v=>{P[k]=k==='title'?v:k==='lives'?Math.round(clamp(v,1,99,3)):k==='timer'?Math.round(clamp(v,0,3600,60)):+v;},()=>{if(k==='bonusCount'){P.bonusCount=Math.round(clamp(P.bonusCount,0,30,3));syncTasks();taskList();fillTask();obstacleList();}});bind('heroFlip',()=>P.heroFlip,v=>P.heroFlip=v);bind('sound',()=>P.sound,v=>P.sound=v);bind('titleEnabled',()=>P.ts.on,v=>P.ts.on=v);for(const [id,key] of [['tsTitle','title'],['tsText','text'],['tsBtn','btn']])bind(id,()=>P.ts[key],v=>P.ts[key]=v);for(const [id,k] of [['tsBg','bg'],['tsBorder','border'],['tsBorderWidth','borderWidth'],['tsTitleFont','titleFont'],['tsTextFont','textFont'],['tsTitleColor','titleColor'],['tsTextColor','textColor'],['tsTitleSize','titleSize'],['tsTextSize','textSize']])bind(id,()=>P.ts[k],v=>P.ts[k]=/Size|Width/.test(k)?+v:v);for(const k of Object.keys(P.d))if(el(k))bind(k,()=>P.d[k],v=>P.d[k]=k.endsWith('Size')?+v:v);for(const k of ['w','l'])for(const [s,key] of [['Title','title'],['Text','text'],['Bg','bg'],['Color','color'],['Btn','btn'],['Label','label']])bind(k+s,()=>P.end[k][key]||(key==='label'?'Переиграть':''),v=>{P.end[k][key]=v;finalKind=k;});taskList();fillTask();obstacleList();renderPreview();}
function taskList(){el('taskList').innerHTML='';P.tasks.forEach((t,i)=>{let b=document.createElement('button');b.className='task'+(sel===i?' active':'');b.innerHTML='<span class="task-number">'+(i+1)+'</span><span><b>'+esc(t.q)+'</b><small>'+types[t.type]+'</small></span>';b.onclick=()=>{sel=i;taskList();fillTask();renderPreview();};el('taskList').append(b);});if(!P.tasks.length)el('taskList').innerHTML='<p class="small">Нет заданий. Нажмите «Добавить новое задание».</p>';el('delTask').disabled=!P.tasks.length;el('saveTask').disabled=!P.tasks.length;el('addTask').disabled=P.tasks.length>=30;}
function fillTask(){const t=P.tasks[sel]||{type:'single',q:'',options:[],ok:'',fb:''};for(const id of ['taskType','taskQ','taskOpt','taskOk','taskFb'])el(id).disabled=!P.tasks.length;for(const [id,k] of [['taskType','type'],['taskQ','q'],['taskOk','ok'],['taskFb','fb']])el(id).value=t[k];el('taskOpt').value=t.options.join('\n');const opts=['single','multiple','order'].includes(t.type);el('taskOpt').disabled=!P.tasks.length||!opts;el('taskOk').disabled=!P.tasks.length||t.type==='oral';}
function readTask(){if(!P.tasks[sel])return null;return {type:el('taskType').value,q:el('taskQ').value,options:el('taskOpt').value.split('\n').map(s=>s.trim()).filter(Boolean),ok:el('taskOk').value,fb:el('taskFb').value};}
function validateTask(t){if(!t.q.trim())return 'Введите вопрос.';if(t.type==='oral')return '';if(t.type==='text')return t.ok.trim()?'':'Введите правильный ответ.';if(t.options.length<2)return 'Добавьте хотя бы два варианта ответа.';const a=t.ok.split(',').map(x=>x.trim());if(a.some(x=>!/^\d+$/.test(x)||+x<1||+x>t.options.length)||new Set(a.map(Number)).size!==a.length)return 'Укажите номера существующих ответов без повторений.';if(t.type==='single'&&a.length!==1)return 'Для этого типа нужен один правильный ответ.';if(t.type==='order'&&a.length!==t.options.length)return 'Укажите порядок всех вариантов, например: 2,1,3.';return '';}
async function saveTask(explicit=false){const t=readTask();if(!t)return;P.tasks[sel]=t;taskList();changed();if(explicit){const error=validateTask(t);if(error){taskNotice(error);return;}const ok=await persist();taskNotice(ok?'Задание '+(sel+1)+' сохранено ✓':'Не удалось записать проект в браузере. Скачайте JSON кнопкой «Сохранить».');}else taskNotice('Изменения задания сохраняются автоматически');}
function addTask(){if(P.tasks.length>=30)return;P.bonusCount=P.tasks.length+1;syncTasks();sel=P.tasks.length-1;el('bonusCount').value=P.bonusCount;taskList();fillTask();obstacleList();changed();taskNotice('Добавлено задание '+P.tasks.length);el('taskQ').focus();}
async function deleteTask(){if(!P.tasks.length)return;const number=sel+1;P.tasks.splice(sel,1);P.bonusCount=P.tasks.length;syncTasks();el('bonusCount').value=P.bonusCount;taskList();fillTask();obstacleList();changed();await persist();taskNotice('Задание '+number+' удалено. Осталось: '+P.tasks.length);}
function obstacleList(){el('obstacleCount').textContent='Бонусов: '+P.bonusCount+' · Препятствий: '+P.obs.length;el('obstacleList').textContent='По одному препятствию перед каждым бонусом. Количество меняется вместе с заданиями.';}
async function upload(file,set,input){if(!file)return;if(!/^image\/(png|jpeg|gif|webp)$/.test(file.type)){notify('Выберите PNG, JPG, WebP или GIF.');input.value='';return;}try{const url=await new Promise((res,rej)=>{let r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file);});await new Promise((res,rej)=>{let im=new Image();im.onload=res;im.onerror=rej;im.src=url;});set(url);changed();await persist();}catch{notify('Изображение не удалось прочитать. Попробуйте другой файл.');}input.value='';}
function assets(){for(const [id,key] of [['heroFile','hero'],['enemyFile','enemy'],['bgFile','bg'],['bonusFile','bonus'],['obFile','ob']])el(id).onchange=e=>upload(e.target.files[0],u=>P.a[key]=u,e.target);for(const [id,obj] of [['tsImg',P.ts],['winFile',P.end.w],['loseFile',P.end.l]])el(id).onchange=e=>upload(e.target.files[0],u=>{obj.img=u;if(id!=='tsImg')finalKind=id==='winFile'?'w':'l';},e.target);function asset(grid,name,url,fn){let b=document.createElement('button');b.className='asset';b.innerHTML='<img alt="" src="'+esc(url)+'"><span>'+esc(name)+'</span>';b.onclick=()=>{fn(url);changed();};el(grid).append(b);}el('heroGrid').replaceChildren();el('enemyGrid').replaceChildren();el('bgGrid').replaceChildren();asset('heroGrid','Герой',B.hb,u=>P.a.hero=u);asset('heroGrid','Героиня',B.hg,u=>P.a.hero=u);asset('enemyGrid','Лиса',B.ef,u=>P.a.enemy=u);asset('enemyGrid','Робот',B.er,u=>P.a.enemy=u);for(const [name,key] of [['Горы','bf'],['Лес','bm'],['Поляна','bn']])asset('bgGrid',name,B[key],u=>{P.a.bg=u;});el('bgSet').onclick=()=>{P.a.bg='';P.a.bf=B.bf;changed();};
// Explicit categories avoid substring matches such as "cat" in unrelated tags.
const gifs=[['Люди','Бегун','1f3c3'],['Люди','Танцовщица','1f483'],['Люди','Танцор','1f57a'],['Животные','Лиса','1f98a'],['Животные','Кот','1f431'],['Животные','Собака','1f436'],['Животные','Лягушка','1f438'],['Спорт','Кубок','1f3c6'],['Спорт','Футбольный мяч','26bd'],['Спорт','Баскетбольный мяч','1f3c0'],['Предметы','Подарок','1f381'],['Предметы','Алмаз','1f48e'],['Предметы','Будильник','23f0'],['Предметы','Робот','1f916'],['Символы','Звезда','2b50'],['Символы','Сердце','2764_fe0f'],['Символы','Искры','2728'],['Препятствия','Камень','1faa8'],['Препятствия','Огонь','1f525'],['Препятствия','Бомба','1f4a3']];
for(const [id,key] of [['heroGif','hero'],['enemyGif','enemy'],['bonusGif','bonus'],['obGif','ob']]){let root=el(id);root.innerHTML='<h4>Библиотека GIF</h4><input placeholder="Поиск по названию" aria-label="Поиск GIF"><div class="catbar"></div><div class="gifGrid"></div>';let cat='Все',q='';const draw=()=>{const grid=root.querySelector('.gifGrid');grid.replaceChildren();for(const [c,name,code] of gifs.filter(([c,n])=>(cat==='Все'||cat===c)&&n.toLowerCase().includes(q))){const u='https://fonts.gstatic.com/s/e/notoemoji/latest/'+code+'/512.gif';let b=document.createElement('button');b.className='asset';b.disabled=true;b.classList.add('loading');b.innerHTML='<img alt=""><span>'+name+'</span>';const gif=b.querySelector('img');gif.onload=()=>{b.disabled=false;b.classList.remove('loading');};gif.onerror=()=>{b.remove();if(!grid.querySelector('button'))grid.textContent='Нет доступных GIF в этой категории. Можно загрузить свой файл.';};gif.src=u;b.onclick=()=>{P.a[key]=u;changed();};grid.append(b);}if(!grid.children.length)grid.textContent='Ничего не найдено';};for(const c of ['Все',...new Set(gifs.map(x=>x[0]))]){let b=document.createElement('button');b.textContent=c;b.className=c===cat?'active':'';b.onclick=()=>{cat=c;root.querySelectorAll('.catbar button').forEach(x=>x.classList.toggle('active',x===b));draw();};root.querySelector('.catbar').append(b);}root.querySelector('input').oninput=e=>{q=e.target.value.trim().toLowerCase();draw();};draw();}}
function titleStyle(card){card.style.background=P.ts.bg;card.style.border=P.ts.borderWidth+'px solid '+P.ts.border;}
function screenHTML(o,kind){const title=kind==='title';return '<div class="screen-icon">'+(kind==='w'?'✦':kind==='l'?'↻':'✧')+'</div>'+(o.img?'<img alt="Иллюстрация" src="'+esc(o.img)+'">':'')+'<h2'+(title?' style="font-family:'+font(o.titleFont)+';font-size:'+o.titleSize+'px;color:'+o.titleColor+'"':'')+'>'+esc(o.title)+'</h2><p'+(title?' style="font-family:'+font(o.textFont)+';font-size:'+o.textSize+'px;color:'+o.textColor+'"':'')+'>'+esc(o.text)+'</p><button class="play" style="background:'+esc(o.btn?.startsWith('#')?o.btn:'#168568')+'">'+esc(kind==='title'?o.btn:o.label||'Переиграть')+'</button>';}
function taskHTML(t,index=sel){if(!t)return '<h2>Добавьте задание</h2><p>Здесь появится его предпросмотр.</p>';let h='<span class="eyebrow">ЗАДАНИЕ '+(index+1)+'</span><h2 style="font-family:'+font(P.d.qFont)+';font-size:'+P.d.qSize+'px;color:'+P.d.qColor+'">'+esc(t.q)+'</h2>';if(['single','multiple','order'].includes(t.type)){h+='<p class="small">'+(t.type==='order'?'Нажмите варианты в правильном порядке':t.type==='multiple'?'Выберите все правильные ответы':'Выберите один ответ')+'</p><div class="answers">';t.options.forEach((x,i)=>h+='<button data-a="'+(i+1)+'" style="font-family:'+font(P.d.aFont)+';font-size:'+P.d.aSize+'px;color:'+P.d.aColor+';background:'+P.d.aBg+'">'+esc(x)+'<span class="order-number"></span></button>');h+='</div>';}else if(t.type==='text')h+='<input class="text-answer" aria-label="Ответ" placeholder="Введите ответ" style="font-family:'+font(P.d.aFont)+';font-size:'+P.d.aSize+'px;color:'+P.d.aColor+';background:'+P.d.aBg+'">';else h+='<p>Ответьте на вопрос устно и нажмите «Готово».</p>';return h+'<p class="feedback" role="status"></p><button class="check play" style="background:'+P.d.btnBg+'">'+(t.type==='oral'?'Готово':'Проверить')+'</button>';}
function renderPreview(){if(test)return;scene();position();hud();const overlay=el('editorOverlay');overlay.replaceChildren();overlay.classList.remove('show');const names={p0:'Игровой мир',p1:'Титульная страница',p2:'Герои',p3:'Мир и препятствия',p4:'Задание '+(sel+1),p5:'Оформление задания',p6:finalKind==='w'?'Экран победы':'Экран поражения'};el('previewTitle').textContent=names[tab];if(['p1','p4','p5','p6'].includes(tab)){let card=document.createElement('div');card.className='editorPanel';if(tab==='p1'){card.innerHTML=screenHTML(P.ts,'title');titleStyle(card);card.querySelector('button').onclick=()=>start(true);}else if(tab==='p6'){let o=P.end[finalKind];card.innerHTML=screenHTML(o,finalKind);card.style.background=o.bg;card.style.color=o.color;card.querySelector('button').onclick=()=>start(true);}else{card.innerHTML=taskHTML(P.tasks[sel]);card.style.background=P.d.cardBg;if(P.tasks[sel])wireAnswer(card,P.tasks[sel],()=>{},true);}overlay.append(card);overlay.classList.add('show');}el('game').classList.toggle('screen-preview',overlay.classList.contains('show'));}
function fallbackImage(role){const shape=role==='bonus'?'<path fill="#ffcf48" stroke="#ca8a17" stroke-width="3" d="M50 6 63 34 94 38 71 59 77 91 50 76 23 91 29 59 6 38 37 34Z"/>':role==='ob'?'<path fill="#8a9da4" stroke="#556b76" stroke-width="3" d="m5 88 10-44 28-29 34 10 19 63Z"/><path fill="#b8c9cc" d="m15 44 28-29 8 31-23 22Z"/>':'<circle cx="50" cy="25" r="16" fill="#2b8a70"/><path fill="#2b8a70" d="M30 45h40v30H58v23H42V75H30Z"/>';return 'data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">'+shape+'</svg>');}
function spriteImage(role){const im=new Image();im.onerror=()=>{im.onerror=null;im.src=fallbackImage(role);};im.src=P.a[role];return im;}
function scene(){const bg=el('far');bg.style.backgroundImage='none';bg.replaceChildren();const u=P.a.bg||P.a.bf;for(let i=0;i<3;i++){const tile=document.createElement('div');tile.className='scenery-tile';tile.style.backgroundImage='url("'+u.replaceAll('"','%22')+'")';bg.append(tile);}el('mid').style.display=el('near').style.display='none';el('world').querySelectorAll('.dyn').forEach(x=>x.remove());for(const [id,size] of [['hero',P.heroSize],['enemy',P.enemySize]]){let im=spriteImage(id);im.id=id;im.className='sprite dyn';im.style.width=im.style.height=size+'px';el('world').append(im);}for(const o of P.obs){let im=spriteImage('ob');im.className='ob dyn';im.dataset.x=o.x;im.style.width=o.w+'px';im.style.height=o.h+'px';el('world').append(im);}for(let i=0;i<P.bonusCount;i++){let im=spriteImage('bonus');im.className='bon dyn';im.dataset.x=480+i*360;im.dataset.task=i;im.style.width=im.style.height=P.bonusSize+'px';el('world').append(im);}}
function sceneryTiles(width,height,cam,speed){const w=Math.max(width,height*16/9),offset=cam*.22*speed,base=Math.floor(offset/w);return Array.from({length:3},(_,j)=>{const i=base+j;return{left:Math.floor(i*w-offset),width:Math.ceil(w)+1,flip:i%2?-1:1};});}
function heroTransform(){return 'scaleX('+((rt?.facing||1)*(P.heroFlip?-1:1))+') scaleY('+(hold.down?.6:1)+')';}
function position(){const r=rt||{x:220,y:0,enemyX:40,cam:0,col:{}},g=el('game').clientHeight*.08;el('hero').style.left=r.x-r.cam+'px';el('hero').style.bottom=g+r.y+'px';el('hero').style.transform=heroTransform();el('enemy').style.left=r.enemyX-r.cam+'px';el('enemy').style.bottom=g+'px';$$('.ob').forEach(o=>{o.style.left=+o.dataset.x-r.cam+'px';o.style.bottom=g+'px';});$$('.bon').forEach(b=>{b.style.left=+b.dataset.x-r.cam+'px';b.style.bottom=g+bonusY()+'px';b.hidden=!!r.col[b.dataset.task];});const tiles=sceneryTiles(el('game').clientWidth,el('game').clientHeight,r.cam,P.par);el('far').querySelectorAll('.scenery-tile').forEach((tile,i)=>{tile.style.width=tiles[i].width+'px';tile.style.left=tiles[i].left+'px';tile.style.transform='scaleX('+tiles[i].flip+')';});}
function bonusY(){return Math.max(120,P.heroSize*.82+24);}
function hud(){el('hLives').textContent='♥ '+(rt?.lives??P.lives);el('hTime').textContent=P.timer?'◷ '+Math.max(0,Math.ceil(rt?.time??P.timer)):'◷ Без таймера';el('hBon').textContent='★ '+Object.keys(rt?.col||{}).length+' / '+P.bonusCount;}
function release(){hold.left=hold.right=hold.down=false;}
function hideModals(){for(const id of ['taskModal','endModal','titleScreen'])el(id).classList.remove('show');}
function start(skip=false){if(!P.tasks.length){notify('Добавьте хотя бы одно задание для запуска игры.');taskNotice('Добавьте задание для запуска игры.');return;}epoch++;cancelAnimationFrame(raf);release();test=true;el('game').classList.add('testing');el('game').classList.remove('screen-preview');el('editorOverlay').classList.remove('show');hideModals();rt={x:220,y:0,facing:1,vx:0,vy:0,enemyX:30,cam:0,col:{},lives:P.lives,time:P.timer,run:false,last:performance.now()};scene();position();hud();if(P.ts.on&&!skip){el('titleCard').innerHTML=screenHTML(P.ts,'title');titleStyle(el('titleCard'));el('titleScreen').classList.add('show');el('titleCard').querySelector('button').onclick=()=>{hideModals();run();};}else run();}
function run(){if(!test)return;release();rt.run=true;rt.last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop);}
function stopGame(){epoch++;cancelAnimationFrame(raf);test=false;rt=null;release();hideModals();el('game').classList.remove('testing');renderPreview();}
function jump(){if(test&&rt?.run&&(rt.y<=.1||P.obs.some(o=>Math.abs(rt.y-o.h)<1&&rt.x+P.heroSize*.8>o.x&&rt.x+P.heroSize*.18<o.x+o.w))){rt.vy=760;beep(460);}}
function heroBox(x,y){return{x:x+P.heroSize*.18,y,w:P.heroSize*.62,h:P.heroSize*.82*(hold.down?.6:1)};}
function intersects(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;}
function step(dt){if(P.timer)rt.time-=dt;rt.enemyX+=P.enemySpeed*26*dt;let dx=Number(hold.right)-Number(hold.left),target=dx*(hold.down?130:285);if(dx)rt.facing=dx;rt.vx+=(target-rt.vx)*Math.min(1,dt*(dx?14:20));let oldY=rt.y;rt.vy-=1550*dt;rt.y=Math.max(0,rt.y+rt.vy*dt);if(rt.y===0)rt.vy=0;let nx=Math.max(0,rt.x+rt.vx*dt),p=heroBox(nx,rt.y);for(const o of P.obs){if(!intersects(p,{x:o.x,y:0,w:o.w,h:o.h}))continue;if(oldY>=o.h-1&&rt.vy<=0){rt.y=o.h;rt.vy=0;}else{nx=rt.vx>=0?o.x-P.heroSize*.8:o.x+o.w-P.heroSize*.18;rt.vx=0;}p=heroBox(nx,rt.y);}rt.x=Math.max(0,nx);rt.cam=Math.max(0,rt.x-Math.min(260,el('game').clientWidth*.36));for(let i=0;i<P.bonusCount;i++)if(!rt.col[i]&&intersects(heroBox(rt.x,rt.y),{x:480+i*360,y:bonusY(),w:P.bonusSize,h:P.bonusSize})){openTask(i);return;}if(rt.enemyX+P.enemySize*.55>=rt.x||P.timer>0&&rt.time<=0||rt.lives<=0)finish(false);}
function loop(now){if(!test||!rt?.run)return;let remaining=Math.min(.05,(now-rt.last)/1000);rt.last=now;while(remaining>0&&rt.run){const dt=Math.min(1/120,remaining);step(dt);remaining-=dt;}position();hud();if(rt.run)raf=requestAnimationFrame(loop);}
function wireAnswer(card,t,done,preview=false){let answers=[],locked=false;const feedback=card.querySelector('.feedback'),check=card.querySelector('.check');card.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{if(locked)return;const v=b.dataset.a;if(t.type==='single')answers=[v];else answers=answers.includes(v)?answers.filter(x=>x!==v):[...answers,v];card.querySelectorAll('[data-a]').forEach(x=>{x.classList.toggle('selected',answers.includes(x.dataset.a));x.setAttribute('aria-pressed',answers.includes(x.dataset.a));x.querySelector('.order-number').textContent=t.type==='order'&&answers.includes(x.dataset.a)?answers.indexOf(x.dataset.a)+1:'';});});check.onclick=()=>{if(locked)return;const text=card.querySelector('.text-answer')?.value.trim()||'';if(t.type==='text'&&!text||['single','multiple','order'].includes(t.type)&&!answers.length){feedback.textContent='Сначала укажите ответ.';return;}let expected=String(t.ok).split(',').map(x=>x.trim()).filter(Boolean),ok=t.type==='oral'||(t.type==='text'?text.toLocaleLowerCase()===String(t.ok).trim().toLocaleLowerCase():t.type==='order'?answers.join(',')===expected.join(','):answers.slice().sort().join(',')===expected.sort().join(','));feedback.textContent=(ok?'Верно! ':'Попробуйте ещё раз. ')+(t.fb||'');feedback.classList.toggle('incorrect',!ok);if(preview)return;locked=true;check.textContent='Продолжить';check.onclick=()=>done(ok);};}
function openTask(i){rt.run=false;release();cancelAnimationFrame(raf);beep(780);let card=el('taskCard');card.style.background=P.d.cardBg;card.innerHTML=taskHTML(P.tasks[i],i);el('taskModal').classList.add('show');wireAnswer(card,P.tasks[i],ok=>{el('taskModal').classList.remove('show');if(ok)rt.col[i]=true;else{rt.lives--;rt.x=Math.max(0,480+i*360-P.heroSize-28);rt.y=0;rt.vy=0;}position();hud();if(rt.lives<=0)return finish(false);if(Object.keys(rt.col).length===P.bonusCount)return finish(true);run();});}
function finish(win){rt.run=false;release();cancelAnimationFrame(raf);const o=P.end[win?'w':'l'];el('endCard').style.background=o.bg;el('endCard').style.color=o.color;el('endCard').innerHTML=screenHTML(o,win?'w':'l')+'<p class="result-stats">★ '+Object.keys(rt.col).length+' / '+P.bonusCount+' &nbsp; ♥ '+rt.lives+'</p><button class="secondary">Начать заново</button>';el('endCard').querySelector('.play').onclick=()=>start(true);el('endCard').querySelector('.secondary').onclick=()=>start(false);el('endModal').classList.add('show');}
function beep(hz){if(!P.sound||!P.vol)return;try{au=au||new(window.AudioContext||window.webkitAudioContext)();au.resume();let o=au.createOscillator(),g=au.createGain();o.connect(g);g.connect(au.destination);o.frequency.value=hz;g.gain.value=.08*P.vol;o.start();g.gain.exponentialRampToValueAtTime(.001,au.currentTime+.12);o.stop(au.currentTime+.12);}catch{}}
function controls(){const keys={ArrowLeft:'left',ArrowRight:'right',ArrowDown:'down',ArrowUp:'up',' ':'up'};document.addEventListener('keydown',e=>{if(!test||!rt?.run||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;const k=keys[e.key];if(!k)return;e.preventDefault();if(k==='up'){if(!e.repeat)jump();}else hold[k]=true;});document.addEventListener('keyup',e=>{if(keys[e.key])hold[keys[e.key]]=false;});window.addEventListener('blur',release);document.addEventListener('visibilitychange',()=>{release();if(rt)rt.last=performance.now();});$$('.controls button').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);if(b.dataset.k==='up')jump();else hold[b.dataset.k]=true;};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>hold[b.dataset.k]=false;});window.addEventListener('resize',()=>{if(test)position();else renderPreview();});}
function download(text,name,type){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([text],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function bytes(s){return new TextEncoder().encode(s).length;}
function sizeLabel(n){return n<1024*1024?(n/1024).toFixed(1)+' КБ':(n/1024/1024).toFixed(2)+' МБ';}
function asDataURL(blob){return new Promise((res,rej)=>{const f=new FileReader();f.onload=()=>res(f.result);f.onerror=rej;f.readAsDataURL(blob);});}
async function optimizeImage(url,limit){
  // GIF and animated WebP stay intact. Only still PNG/JPEG images are recompressed.
  if(!/^data:image\/(png|jpeg|jpg);/i.test(url))return url;
  try{const im=await new Promise((res,rej)=>{const image=new Image();image.onload=()=>res(image);image.onerror=rej;image.src=url;});
    const scale=Math.min(1,limit/Math.max(im.naturalWidth,im.naturalHeight)),canvas=document.createElement('canvas');
    canvas.width=Math.max(1,Math.round(im.naturalWidth*scale));canvas.height=Math.max(1,Math.round(im.naturalHeight*scale));
    const ctx=canvas.getContext('2d');if(!ctx)return url;ctx.drawImage(im,0,0,canvas.width,canvas.height);
    const smaller=canvas.toDataURL('image/webp',.8);return smaller.length<url.length?smaller:url;
  }catch{return url;}
}
async function embeddedProject(compact){
  const project=JSON.parse(JSON.stringify(P));
  // These source pictures are editor choices, not layers used by the game.
  project.a.bm=project.a.bn='';if(project.a.bg)project.a.bf='';
  const cache=new Map();
  for(const [obj,key,limit] of [...Object.keys(project.a).map(k=>[project.a,k,['bg','bf'].includes(k)?1440:512]),[project.ts,'img',800],[project.end.w,'img',800],[project.end.l,'img',800]]){
    const u=obj[key];if(!u)continue;
    const cacheKey=u+'|'+limit;
    if(!cache.has(cacheKey)){let data=u;if(!u.startsWith('data:')){try{const r=await fetch(u);if(!r.ok)throw Error();data=await asDataURL(await r.blob());}catch{if(obj===project.a&&['bonus','ob','hero','enemy'].includes(key))data=fallbackImage(key);else throw Error('Не удалось загрузить изображение для экспорта. Замените недоступную картинку.');}}
      cache.set(cacheKey,compact?await optimizeImage(data,limit):data);
    }obj[key]=cache.get(cacheKey);
  }return project;
}
async function packHTML(html){
  if(typeof CompressionStream==='undefined'||typeof DecompressionStream==='undefined')return html;
  try{const buffer=await new Response(new Blob([html]).stream().pipeThrough(new CompressionStream('gzip'))).arrayBuffer();
    let binary='';const data=new Uint8Array(buffer);for(let i=0;i<data.length;i+=8192)binary+=String.fromCharCode(...data.subarray(i,i+8192));
    const encoded=btoa(binary);
    const loader='(async()=>{try{const b=Uint8Array.from(atob('+JSON.stringify(encoded)+'),c=>c.charCodeAt(0));const h=await new Response(new Blob([b]).stream().pipeThrough(new DecompressionStream("gzip"))).text();document.open();document.write(h);document.close();}catch{document.body.textContent="Не удалось открыть сжатую игру. Используйте свежую версию браузера или обычный HTML.";}})();';
    const packed='<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(P.title)+'</title><body><p>Загружаем игру…</p><script>'+loader+'</script></body></html>';
    return bytes(packed)<bytes(html)?packed:html;
  }catch{return html;}
}
async function standalone(compact=false){
  const read=async url=>{const r=await fetch(url);if(!r.ok)throw Error('Не удалось загрузить файлы игры');return r.text();};
  const [css,js,project]=await Promise.all([read('dogoni_app.css?v=4'),read('dogoni_app.js?v=4'),embeddedProject(compact)]);
  const game=el('game').cloneNode(true);game.className='game';game.querySelectorAll('.dyn,.scenery-tile').forEach(x=>x.remove());
  for(const id of ['editorOverlay','taskCard','endCard','titleCard'])game.querySelector('#'+id).replaceChildren();
  game.querySelectorAll('.show').forEach(x=>x.classList.remove('show'));
  const safe=s=>s.replace(/<\/script/gi,'<\\/script');
  const out='<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(P.title)+'</title><style>'+(compact?css.replace(/\/\*[\s\S]*?\*\//g,'').replace(/\s+/g,' ').replace(/\s*([{}:;,])\s*/g,'$1'):css)+'body{margin:0}.game{width:100vw!important;height:100dvh!important;max-height:none!important;border-radius:0!important;aspect-ratio:auto!important}.badge{display:none}</style><body>'+game.outerHTML+'<script>window.DOGONI_PROJECT='+safe(JSON.stringify(project))+';</script><script>'+safe(js)+'</script></body></html>';
  return compact?packHTML(out):out;
}
function iframeCode(html){return '<iframe title="'+esc(P.title)+'" style="width:100%;height:100%;min-height:540px;border:0" srcdoc="'+esc(html)+'"></iframe>';}
async function exportGame(mode){
  if(!P.tasks.length){notify('Добавьте хотя бы одно задание перед экспортом.');return;}
  const error=P.tasks.map((t,i)=>validateTask(t)?'Задание '+(i+1)+': '+validateTask(t):'').find(Boolean);if(error){notify(error);return;}
  if(mode==='copy'&&preparedExport?.revision===revision){try{await navigator.clipboard.writeText(preparedExport.iframe);notify('Код для Genially скопирован'+(preparedExport.compact?' — облегчённая версия.':'.'));}catch{notify('Буфер обмена недоступен. Разрешите копирование в браузере или скачайте HTML.');}return;}
  const currentRevision=revision;const buttons=['miniBtn','htmlBtn','copyBtn'].map(el);buttons.forEach(b=>b.disabled=true);notify(mode==='mini'?'Уменьшаем изображения и сжимаем код…':'Подготавливаем игру…');
  try{
    if(mode==='mini'){
      const original=await standalone(false),compact=await standalone(true);if(revision!==currentRevision){notify('Проект изменился во время подготовки. Нажмите «Облегчить код» ещё раз.');return;}
      const before=bytes(iframeCode(original));const best=bytes(iframeCode(compact))<before?compact:original;const iframe=iframeCode(best),after=bytes(iframe);
      preparedExport={revision,html:best,iframe,compact:true};el('miniBtn').setAttribute('aria-pressed','true');el('exportStatus').textContent='Код для Genially: '+sizeLabel(before)+' → '+sizeLabel(after)+' (−'+Math.round((1-after/before)*100)+'%). GIF сохранены с анимацией.';
      notify('Готово. Нажмите «Копировать для Genially».');
    }else{
      const html=preparedExport?.revision===revision?preparedExport.html:await standalone(false);
      if(revision!==currentRevision){notify('Проект изменился. Повторите экспорт.');return;}
      if(mode==='copy'){preparedExport={revision,html,iframe:iframeCode(html),compact:false};try{await navigator.clipboard.writeText(preparedExport.iframe);notify('Код для Genially скопирован.');}catch{notify('Код подготовлен. Нажмите «Копировать для Genially» ещё раз.');}}
      else{download(html,preparedExport?.compact?'dogoni-compact.html':'dogoni-game.html','text/html');notify('Игра сохранена в HTML');}
    }
  }catch(e){notify('Экспорт не завершён: '+e.message);}finally{buttons.forEach(b=>b.disabled=false);}
}

function events(){controls();$$('.tabs button').forEach(b=>b.onclick=()=>{if(test)stopGame();tab=b.dataset.tab;$$('.tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.pane').forEach(x=>x.classList.toggle('active',x.id===tab));renderPreview();});for(const id of ['taskType','taskQ','taskOpt','taskOk','taskFb'])el(id).oninput=()=>{saveTask();if(id==='taskType')fillTask();};el('saveTask').onclick=()=>saveTask(true);el('addTask').onclick=addTask;el('delTask').onclick=deleteTask;el('previewWin').onclick=()=>{finalKind='w';renderPreview();};el('previewLose').onclick=()=>{finalKind='l';renderPreview();};el('testBtn').onclick=()=>start();el('stop').onclick=stopGame;el('saveBtn').onclick=()=>{saveTask();persist();download(JSON.stringify(P,null,2),'dogoni-project.json','application/json');};el('loadBtn').onclick=()=>el('loadFile').click();el('loadFile').onchange=async e=>{try{if(!e.target.files[0])return;P=normalize(JSON.parse(await e.target.files[0].text()));invalidateExport();syncTasks();stopGame();fill();assets();await persist();notify('Проект загружен');}catch{notify('Не удалось загрузить проект. Выберите JSON-файл редактора.');}e.target.value='';};el('htmlBtn').onclick=()=>exportGame('html');el('miniBtn').onclick=()=>exportGame('mini');el('copyBtn').onclick=()=>exportGame('copy');el('cont').onclick=()=>{el('resume').classList.remove('show');notify('Продолжаем редактирование');};el('startNew').onclick=async()=>{P=def();invalidateExport();sel=0;syncTasks();fill();assets();el('resume').classList.remove('show');await persist();};window.addEventListener('pagehide',()=>{if(!embedded)persist();});}
async function init(){if(embedded){P=normalize(embedded);syncTasks();controls();start();return;}db=await openDB();stored=await dbGet();if(!stored)try{stored=JSON.parse(localStorage.getItem('dogoniProject'));}catch{}if(stored)try{P=normalize(stored);}catch{notify('Сохранённый проект повреждён. Загружены исходные настройки.');stored=null;}syncTasks();fill();assets();events();if(stored)el('resume').classList.add('show');else await persist();}
init();
})();
